//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBS2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;//dodali da bi ukljucili anotaciju radi serverske validacije
    using System.Web.Mvc;//ukljucili

    public partial class Korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnici()
        {
            this.Zahtevi = new HashSet<Zahtevi>();
        }

        public int KorisnikId { get; set; }
        public int UlogaID { get; set; }
        [Required(ErrorMessage = "Unesite ime korisnika")]
        [Display(Name = "Korisničko ime")]
        public string NazivKorisnika { get; set; }

        [Required(ErrorMessage = "Unesite lozinku")]
        [DataType(DataType.Password)]
        public string Lozinka { get; set; }
        [Required(ErrorMessage = "Unesite mail")]
        [EmailAddress(ErrorMessage = "Unesite pravilnu e-mail adresu")]
        [Display(Name = "Email")]

        public string Email { get; set; }

        public virtual Uloga Uloga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zahtevi> Zahtevi { get; set; }
    }
}

